version: 0.2

env:
  variables:
    BUILD_NUMBER: "0.1"

phases:
  install:
    commands:
    - pip install -r requirements.txt
    - sudo apt-get install zip unzip -qy
  build:
    commands:
    - echo Build started on `date`
    - zip -r app app
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - app.zip
  name: data-processor-$BUILD_NUMBER


