version: 0.2

env:
  variables:
    BUILD_NUMBER: "0.1"

phases:
  install:
    commands:
    - echo Nothing to do in the install phase...
  pre_build:
    commands:
    - echo Nothing to do in the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
#    - sbt package
    - zip -r app app
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  discard-paths: true
  files:
  - app.zip
  name: data-processor-BUILD_NUMBER.zip


