version: 0.2

env:
  variables:
    BUILD_NUMBER: "0.1"

phases:
  install:
    commands:
    - pip install -r requirements.txt
    - sudo apt-get update
    - sudo apt install openjdk-8-jre -qy
    - sudo update-alternatives --config java
    - which java
    - java -version
    - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
    - echo $JAVA_HOME
    - sudo apt-get install zip unzip -qy
  pre_build:
    commands:
    - ./run-tests.py -d tests/unit
    - ./run-tests.py -d tests/regression
  build:
    commands:
    - echo Build started on `date`
    - zip -r app app
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - app.zip
  name: data-processor-$BUILD_NUMBER


